# Logger config:
log_mask: -1
log_path: ../logs/
run_counter_path: ../logs/run_counter
logger_address: tcp://*:6666

# Time sync:
time_sync_period_ms: 5000
time_sync_address: 224.0.0.100
time_sync_port: 50000

# Sensors config:
sensor_multicast_address: 224.0.0.100
sensor_multicast_port: 1234
sensor_multicast_interface: "192.168.44.35"
accelerometer_calibration: true
accelerometer_R:
  - 1
  - 0
  - 0
  - 0
  - 1
  - 0
  - 0
  - 0
  - 1
accelerometer_bias:
  - 0
  - 0
  - 0

# EKF parameters:
position_process_noise: 0.00999999978
velocity_process_noise: 0.00999999978
quaterion_process_noise: 0.00999999978
gyro_bias_process_noise: 0.00999999978
drawbar_process_noise: 0.00999999978
accel_measurement_noise: 0.00999999978
pos_provider_measurement_noise: 0.00999999978
constraint_correction_scaler: 0.00999999978
constraint_correction_repeats: 3
drawbar_length: 0

# Other:
loop_rate_ms: 5
debug_mode: true

# Plugins:
force_sensor_ips:
  []